#!/usr/bin/env python3
"""Generate train image lists for joint v2 training.

Joint v1 used uniform sampling across data/yolo/duke_160/ (5024 train tiles)
and data/yolo/naip/ (174 train tiles). The 29:1 ratio meant gradients were
overwhelmingly Duke and NAIP test mAP regressed from 0.563 -> 0.275.

This script writes two text files of absolute image paths:
  - train_naip_oversampled.txt: each NAIP tile repeated N times (default 29)
  - train_duke.txt: each Duke 160 tile once

duke_naip_combined_v2.yaml points at these files via the train: list.
Re-run on each machine because the paths are absolute.

Note: ~15% of Duke chips (~753/5024) have empty label files. These are intentional
zero-annotation tiles (160 px chips with no solar arrays) and act as negative
examples — not a bug. YOLO requires the empty .txt file to match the .png.
"""

from __future__ import annotations

import argparse
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
NAIP_ROOT = REPO_ROOT / "data" / "yolo" / "naip"
DUKE_ROOT = REPO_ROOT / "data" / "yolo" / "duke_160"
NAIP_TRAIN = NAIP_ROOT / "images" / "train"
DUKE_TRAIN = DUKE_ROOT / "images" / "train"
OUT_DIR = REPO_ROOT / "data" / "yolo" / "joint_v2"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build joint v2 train lists")
    parser.add_argument(
        "--naip-repeat",
        type=int,
        default=29,
        help="Number of times each NAIP tile is repeated. Default 29 brings "
             "the effective ratio close to 1:1 against Duke 160's ~5024 tiles.",
    )
    return parser.parse_args()


def list_images(directory: Path) -> list[Path]:
    exts = {".png", ".jpg", ".jpeg"}
    return sorted(p for p in directory.iterdir() if p.suffix.lower() in exts)


def main() -> int:
    args = parse_args()

    if not NAIP_TRAIN.exists():
        raise FileNotFoundError(f"NAIP train dir not found: {NAIP_TRAIN}")
    if not DUKE_TRAIN.exists():
        raise FileNotFoundError(f"Duke 160 train dir not found: {DUKE_TRAIN}")

    naip_imgs = list_images(NAIP_TRAIN)
    duke_imgs = list_images(DUKE_TRAIN)
    if not naip_imgs:
        raise ValueError(f"No images under {NAIP_TRAIN}")
    if not duke_imgs:
        raise ValueError(f"No images under {DUKE_TRAIN}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    naip_out = OUT_DIR / "train_naip_oversampled.txt"
    duke_out = OUT_DIR / "train_duke.txt"
    yaml_out = OUT_DIR / "data.yaml"

    with naip_out.open("w") as f:
        for _ in range(args.naip_repeat):
            for img in naip_imgs:
                f.write(f"{img}\n")

    with duke_out.open("w") as f:
        for img in duke_imgs:
            f.write(f"{img}\n")

    naip_val = NAIP_ROOT / "images" / "val"
    naip_test = NAIP_ROOT / "images" / "test"
    duke_test = DUKE_ROOT / "images" / "test"

    yaml_text = (
        "# Auto-generated by scripts/02g_build_joint_v2_lists.py.\n"
        "# Re-run on every machine — paths are absolute.\n"
        "\n"
        "train:\n"
        f"  - {naip_out}\n"
        f"  - {duke_out}\n"
        "\n"
        "val:\n"
        f"  - {naip_val}\n"
        "\n"
        "test:\n"
        f"  - {naip_test}\n"
        f"  - {duke_test}\n"
        "\n"
        "nc: 1\n"
        "names:\n"
        "  0: solar_array\n"
    )
    yaml_out.write_text(yaml_text)

    naip_lines = len(naip_imgs) * args.naip_repeat
    duke_lines = len(duke_imgs)
    ratio = naip_lines / duke_lines if duke_lines else float("inf")

    print(f"NAIP unique tiles: {len(naip_imgs)}")
    print(f"NAIP oversample factor: {args.naip_repeat}x")
    print(f"NAIP lines written: {naip_lines}  -> {naip_out}")
    print(f"Duke unique tiles: {duke_lines}  -> {duke_out}")
    print(f"Effective NAIP:Duke ratio in train batches: {ratio:.2f}:1")
    print(f"Generated data.yaml -> {yaml_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
